@isTest
private class AdvisorOfficeHomeControllerTest {

    static testMethod void myUnitTest() 
    {
        // TO DO: implement unit test
        AdvisorOfficeHomeController objAdvisorOfficeHomeController=new AdvisorOfficeHomeController();
        
        objAdvisorOfficeHomeController.displayPopUp = false;
        objAdvisorOfficeHomeController.displayPopUpAboutUs = false;
        objAdvisorOfficeHomeController.displayPopUpContactUs = false;
        objAdvisorOfficeHomeController.displayPopUpLogin = false;
        
        objAdvisorOfficeHomeController.name = 'AdvisorFactory';
        objAdvisorOfficeHomeController.email = 'prajakta.sanap@eternussolutions.com';
        
        objAdvisorOfficeHomeController.closePopUp();
        objAdvisorOfficeHomeController.showPopUp();
        objAdvisorOfficeHomeController.showPopUpAboutUs();
        objAdvisorOfficeHomeController.showPopUpContactUs();
        objAdvisorOfficeHomeController.showPopUpLogin();
        objAdvisorOfficeHomeController.getPageReference();
        objAdvisorOfficeHomeController.cancel();
		objAdvisorOfficeHomeController.send();        
        
        
        
    }
}