/*
	Revision History:
	
    Version     Version Author     Date           Comments
    1.0         Gaurav            07/01/2013     This Class is used to send attachement thorugh mail to lead or entity after inserting 
    											  attachment
    
*/

public with sharing class AttachmentHandler {
	
	public void OnAfterInsert(List<Attachment> pNewRecords){
		
		//FinancialWellnessController financialWellness = new FinancialWellnessController();
		//financialWellness.sendAttachmentMail(pNewRecords[0].ParentId);	
		
	}
}