@isTest
private class EmailFunctionalityTest {

	static testmethod void testEmailFunctionality(){
		test.startTest();
		/*List<Lead> lstLead = new List<Lead>();
		Lead objLead = New Lead(LastName='ABC',Company='TestCompany');
		insert objLead;
		lstLead.add(objLead);
		
		List<User> lstUser = [Select u.IsActive, u.Id From User u Where u.IsActive = True];
		
		Account objAcc = new Account();
		objAcc.FirstName = 'FName';
		objAcc.LastName = 'LName';
		insert objAcc;
		List<Account> lstAccount = New List<Account>();
		lstAccount.add(objAcc);
		EmailFunctionality.SendNewsLetters(lstUser,lstLead,lstAccount); // 76%
		//List<String> lstString = EmailFunctionality.CreateMasterEmailList(lstUser, lstLead);
		*/
		test.stopTest();
	}

}