/**
 * @Author: Samruddhi P
 * @since : 17th Feb 2011
 * @Description: EmergencyActionPlanBean is bean class for EmergencyPlanningPage in Analysis Section
 */
public class EmergencyActionPlanBean{
    public String ObjectName {get; set;}
    public String Name {get; set;}
    public String Owner {get; set;}
    public Double Amount {get; set;}
    public String Action {get; set;}
        
    /**
    * Constructor to initialise the bean class
    */  
    public EmergencyActionPlanBean(){
        Amount=0;
    }
}