/**
 * @Author: Samruddhi P
 * @since : 18th Feb 2011
 * @Description: LifeInsurancePlanningController is controller class for LifeInsuranceOutputComponent in Analysis Section
 */
public class LifeInsurancePlanningController{
    public LifeInsurancePlanningBean bean {get; set;}
    public Account entity {get; set;}
    public Account spouse {get; set;}
    public Insurance__c insurance {get; set;} 
    public String selAdjustmentFactor {get; set;} 

    /**
    * @Description: Constructor to initialise the bean class,service class and fetch existing data
    * @param: None 
    */
    public LifeInsurancePlanningController(){
    }

}