public class SalContactHandler 
{
     static Boolean flag=true;
     public Integer count=0;
     
/*	public void beforeContactInsert(List<Contact> lstContact)
	{
		Map<Double , List<Contact>> mapPortalIdAndContactId = new Map<Double , List<Contact> >();
	
		for(Contact cont : lstContact)
		{
			if(cont.Portal_Id__c!= NULL )
			{
				  if(!mapPortalIdAndContactId.containsKey(cont.Portal_Id__c))
				   {
					 mapPortalIdAndContactId.put(cont.Portal_Id__c , new List<Contact>{cont});
				   }
					else
					{
					mapPortalIdAndContactId.get(cont.Portal_Id__c).add(cont);
					}
			}
		}
		List<Account> lstAccount = new List<Account>([select id, Portal_Id__c , Name  from Account where Portal_Id__c IN: mapPortalIdAndContactId.keySet() ]);
		//system.debug('***********************************************************************1.1'+lstAccount);
		
		for(Account objAccount : lstAccount )
		{
			if(mapPortalIdAndContactId != null && mapPortalIdAndContactId.containsKey(objAccount.Portal_Id__c) && mapPortalIdAndContactId.get(objAccount.Portal_Id__c) != null)
			{
				for(Contact objContact : mapPortalIdAndContactId.get(objAccount.Portal_Id__c))
				{
				   	
				   if(objAccount.Id != null)
				   		objContact.AccountId = objAccount.Id;
					system.debug('objContact======='+objContact);
					count++;
				}
			}
		}
		system.debug('***********************************************************************1.1'+count);
	} */
}