public class TestSendDiscontinuatonSMS 
{
	@isTest(SeeAllData = true)
    static void testDiscontinueSMS() 
    {
        List<Account> accounts;
	
    	/*Account acc = new Account(FirstName='Test_Fname1',LastName='Test_Renewal_Lname',Entity_Status__c='Active',Discontinuation_SMS_Sent__c=false,PersonMobilePhone='9876543210');

		insert acc;
		accounts= [select Id,Discontinuation_SMS_Sent__c from Account where LastName = 'Test_Renewal_Lname'];
		accounts[0].Discontinuation_SMS_Sent__c=true;
		update accounts[0];*/
    }
}